import { CountResult, DatasetOverview, GroupResult, IpsDetail, SearchResult } from '../models/ips.model';
import { CategoryDatum, MapMetric, VisualizationProvenance, VisualizationSpec } from '../models/visualization.model';
import { TrackedQuery } from './conversation-store.service';

const DONUT_MAX_CATEGORIES = 6;

const METRIC_UNITS: Record<GroupResult['metric'], string> = {
  registros: 'registros (líneas de capacidad)',
  prestadores: 'prestadores únicos',
  sedes: 'sedes únicas',
  capacidad_instalada: 'unidades de capacidad instalada',
};

const DIMENSION_TITLES: Record<string, string> = {
  departamento: 'departamento',
  municipio: 'municipio',
  naturaleza: 'naturaleza jurídica',
  num_nivel_atencion: 'nivel de atención',
  nom_grupo_capacidad: 'grupo de capacidad',
  nom_descripcion_capacidad: 'tipo de capacidad',
};

/**
 * Deterministically derives dashboard visualizations from a completed tool result.
 * Only values present in the official API response are used; nothing is generated by the LLM.
 */
export function buildVisualizations(query: TrackedQuery): VisualizationSpec[] {
  if (query.status !== 'completed' || !query.result) return [];
  switch (query.tool) {
    case 'count_ips':
      return fromCount(query, query.result as CountResult);
    case 'group_ips':
      return fromGroup(query, query.result as GroupResult);
    case 'search_ips':
      return fromSearch(query, query.result as SearchResult);
    case 'get_ips_details':
      return fromDetail(query, query.result as IpsDetail);
    case 'get_dataset_overview':
      return fromOverview(query, query.result as DatasetOverview);
    default:
      return [];
  }
}

function provenance(query: TrackedQuery, metadata: VisualizationProvenance['metadata']): VisualizationProvenance {
  return { queryId: query.queryId, tool: query.tool, metadata };
}

function scope(filters: Record<string, string>): string {
  const parts = Object.values(filters);
  return parts.length ? ` · ${parts.join(' · ')}` : ' · Colombia';
}

function fromCount(query: TrackedQuery, r: CountResult): VisualizationSpec[] {
  return [
    {
      id: `${query.queryId}-metric`,
      kind: 'metric',
      title: `Conteo de IPS${scope(r.metadata.filters)}`,
      description: 'Cada fila del dataset es una línea de capacidad instalada; prestadores y sedes son conteos únicos.',
      unit: 'prestadores únicos, sedes únicas y registros',
      provenance: provenance(query, r.metadata),
      items: [
        { label: 'Prestadores únicos', value: r.prestadores, unit: 'prestadores', emphasis: true },
        { label: 'Sedes únicas', value: r.sedes, unit: 'sedes' },
        { label: 'Registros', value: r.registros, unit: 'líneas de capacidad' },
      ],
    },
  ];
}

function fromGroup(query: TrackedQuery, r: GroupResult): VisualizationSpec[] {
  const data: CategoryDatum[] = r.buckets.map((b) => ({ label: b.label, value: b.value }));
  const unit = METRIC_UNITS[r.metric];
  const dimension = DIMENSION_TITLES[r.dimension] ?? r.dimension;
  const base = {
    title: `${capitalize(unitNoun(r.metric))} por ${dimension}${scope(r.metadata.filters)}`,
    description: r.metric_description,
    unit,
    provenance: provenance(query, r.metadata),
  };
  const specs: VisualizationSpec[] = [];
  if (r.dimension === 'departamento' && isMapMetric(r.metric) && data.length) {
    specs.push({ ...base, id: `${query.queryId}-map`, kind: 'colombia_map', metric: r.metric, data });
  }
  const chartKind = data.length <= DONUT_MAX_CATEGORIES && r.dimension !== 'departamento' ? 'donut_chart' : 'horizontal_bar';
  specs.push({ ...base, id: `${query.queryId}-chart`, kind: chartKind, data });
  specs.push({
    ...base,
    id: `${query.queryId}-table`,
    kind: 'table',
    columns: [
      { key: 'label', label: capitalize(dimension) },
      { key: 'value', label: capitalize(unit), numeric: true },
    ],
    rows: data.map((d) => ({ label: d.label, value: d.value })),
  });
  return specs;
}

function fromSearch(query: TrackedQuery, r: SearchResult): VisualizationSpec[] {
  return [
    {
      id: `${query.queryId}-table`,
      kind: 'table',
      title: `Sedes encontradas${scope(r.metadata.filters)}`,
      description: `${r.total_sedes} sedes coinciden; se muestra la página ${r.page}.`,
      unit: 'sedes',
      provenance: provenance(query, r.metadata),
      columns: [
        { key: 'sede', label: 'Sede' },
        { key: 'prestador', label: 'Prestador' },
        { key: 'ubicacion', label: 'Ubicación' },
        { key: 'naturaleza', label: 'Naturaleza' },
        { key: 'nivel', label: 'Nivel' },
      ],
      rows: r.items.map((s) => ({
        sede: s.nombre_sede,
        prestador: s.nombre_prestador,
        ubicacion: `${s.municipio}, ${s.departamento}`,
        naturaleza: s.naturaleza ?? 'Sin dato',
        nivel: s.nivel_atencion ?? 'Sin dato',
      })),
    },
  ];
}

function fromDetail(query: TrackedQuery, r: IpsDetail): VisualizationSpec[] {
  return [
    {
      id: `${query.queryId}-table`,
      kind: 'table',
      title: r.site.nombre_sede,
      description: `${r.site.nombre_prestador} · ${r.site.municipio}, ${r.site.departamento}`,
      unit: 'capacidad instalada',
      provenance: provenance(query, r.metadata),
      columns: [
        { key: 'grupo', label: 'Grupo' },
        { key: 'descripcion', label: 'Tipo' },
        { key: 'cantidad', label: 'Cantidad', numeric: true },
      ],
      rows: r.capacidades.map((c) => ({ grupo: c.grupo, descripcion: c.descripcion, cantidad: c.cantidad })),
    },
  ];
}

function fromOverview(query: TrackedQuery, r: DatasetOverview): VisualizationSpec[] {
  return [
    {
      id: `${query.queryId}-metric`,
      kind: 'metric',
      title: r.name,
      description: r.attribution ?? 'Fuente oficial',
      unit: 'prestadores únicos, sedes únicas y registros',
      provenance: provenance(query, r.totals.metadata),
      items: [
        { label: 'Prestadores únicos', value: r.totals.prestadores, unit: 'prestadores', emphasis: true },
        { label: 'Sedes únicas', value: r.totals.sedes, unit: 'sedes' },
        { label: 'Registros', value: r.totals.registros, unit: 'líneas de capacidad' },
      ],
    },
  ];
}

function isMapMetric(metric: GroupResult['metric']): metric is MapMetric {
  return metric === 'sedes' || metric === 'registros';
}

function unitNoun(metric: GroupResult['metric']): string {
  return metric === 'capacidad_instalada' ? 'capacidad instalada' : metric;
}

function capitalize(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1);
}
